[I 10:41:37.123 NotebookApp] Serving notebooks from local directory: /home/geny/Documents/covid-19/casos_provincia
[I 10:41:37.123 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 10:41:37.123 NotebookApp] http://localhost:8888/
[I 10:41:37.123 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 10:41:46.019 NotebookApp] 302 GET / (::1) 1.320000ms
[I 10:41:46.041 NotebookApp] 302 GET /tree? (::1) 1.960000ms
[I 10:41:47.941 NotebookApp] 302 POST /login?next=%2Ftree%3F (::1) 71.080000ms
[W 10:41:53.285 NotebookApp] Notebook data_casos_provincia.ipynb is not trusted
[I 10:41:54.304 NotebookApp] Kernel started: e47adb9f-1d52-47be-b5ef-07e2beac8954, name: python3
[W 10:41:54.349 NotebookApp] 404 GET /nbextensions/pydeck/extension.js?v=20210824104136 (::1) 16.010000ms referer=http://localhost:8888/notebooks/data_casos_provincia.ipynb
[W 10:41:54.436 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20210824104136 (::1) 3.860000ms referer=http://localhost:8888/notebooks/data_casos_provincia.ipynb
[I 10:43:05.370 NotebookApp] Starting buffering for e47adb9f-1d52-47be-b5ef-07e2beac8954:5559ef5b117b4c0b8ee89f775403ecb4
[I 10:43:05.786 NotebookApp] Kernel restarted: e47adb9f-1d52-47be-b5ef-07e2beac8954
[I 10:43:05.806 NotebookApp] Restoring connection for e47adb9f-1d52-47be-b5ef-07e2beac8954:5559ef5b117b4c0b8ee89f775403ecb4
[I 10:43:06.842 NotebookApp] Replaying 3 buffered messages
[I 10:43:48.411 NotebookApp] Kernel interrupted: e47adb9f-1d52-47be-b5ef-07e2beac8954
[I 10:43:54.294 NotebookApp] Saving file at /data_casos_provincia.ipynb
[I 10:45:54.290 NotebookApp] Saving file at /data_casos_provincia.ipynb
[I 10:47:54.290 NotebookApp] Saving file at /data_casos_provincia.ipynb
[I 10:51:54.289 NotebookApp] Saving file at /data_casos_provincia.ipynb
[I 10:52:55.376 NotebookApp] Starting buffering for e47adb9f-1d52-47be-b5ef-07e2beac8954:5559ef5b117b4c0b8ee89f775403ecb4
